goatee-gtk.cabal: drop 'Test' from 'other-modules'
ghc-8.4 mastered check of module completeness and now
detects Main/non-Main module conflict:

    Building test suite 'test-goatee-gtk' for goatee-gtk-0.3.1.2..

    tests/Test.hs:18:8: error:
        File name does not match module name:
        Saw: ‘Main’
        Expected: ‘Test’
       |
    18 | module Main (main) where
       |        ^^^^

The change drops 'Test' form 'other-modules'
and leaves it only for 'Main-is' entry.

This fixes test build and and keeps tests passing on ghc-8.4

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>